### ISSUE TITLE
Task to migrate Inventory Statistical Code Types and Stastistical Codes

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#113]

**Comment by ahafele** [comment]
I have created the code types and codes on folio-test for all that have been confirmed so far per https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/240. 

@dlrueda these are ready for the next load. 
@jgreben or @jermnelson could this ticket be done before the next time we wipe folio-test?

**Comment by jgreben** [comment]
I will create that task.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio-tasks/pull/127
