### ISSUE TITLE
Add task to pull and load courses processing statuses

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss-deprecated/folio-migration-tasks#147]
Need to grab Settings > Courses > Processing statuses from folio-test. See https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/280#issuecomment-1400805947 . Apparently one of them is reference data that comes with folio that didn't get loaded to folio-dev.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio-tasks/pull/new/147-courses-processing-status
