### ISSUE TITLE
Create task to pull Item note types from one version to another

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#152]

**Comment by shelleydoljack** [comment]
we're getting these from the spreadsheet in folio ops drive: https://drive.google.com/drive/folders/1Nn-PNgniSUH3b_Hi6f2NMNLCXYCWU7Um?usp=share_link

**Comment by ahafele** [comment]
Ah ok, in that case there are some missing and I'll just update the spreadsheet

**Comment by shelleydoljack** [comment]
It looks like maybe @jgreben might have a local copy of item-note-types.tsv that includes HVSHELFLOC but not the one you added to folio-dev, Circ staff, that needs to be updated in the Folio Ops drive.
