### ISSUE TITLE
Load permissions_sets.json in an ordered way

### ISSUE THREAD

**Issue by jgreben** [sul-dlss-deprecated/folio-migration-tasks#167]
Idea 1: use a text file of config settings list that has the ordered permissions (i.e. permissions that are the subPermissions of subsequent permissions) and then use that list to query the permission_sets.json to load a single permission set at a time into folio.

Other ideas...? ¯\_(ツ)_/¯

**Comment by jgreben** [comment]
@shelleydoljack do we have somewhere the order in which they need to be loaded?

**Comment by shelleydoljack** [comment]
Not really. The psets are nested, so each level should be loaded before the next. For instance, Cataloging 1 needs to loaded before Cataloging 2. It might be that Access 7 could contain the pset for Cataloging 2, so the rule should be: load all the 1's together, then all the 2's together, etc.

**Comment by jgreben** [comment]
I see in the log, e.g.: `     "Attempting to add non-existent permissions 14c817a6-8a9c-4cb4-8b0b-ae090dcdf86e as sub-permissions to permission 6c6f149e-becd-4211-8cea-28b909ac5dc1"`

So I guess it could be determined that way if there is not already a list of the order.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio-tasks/184
