### ISSUE TITLE
Add more modules to configurations rake task

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss-deprecated/folio-migration-tasks#185]
Need to add more values to the `config/settings/prod.yml` file configurations entry (and any *.yaml files used locally). The complete list should be:
```
configurations:
  - edge-sip2
  - BULKEDIT
  - CHECKOUT
  - FAST_ADD
  - INVOICE
  - LOAN_HISTORY
  - CHECKOUT
  - FAST_ADD
  - INVOICE
  - ORDERS
  - ORG
  - SETTINGS
  - TENANT
  - USERSBL
```
`SMTP_SERVER` is no longer configured through okapi config entries in Nolana. Per the [mod-email readme](https://github.com/folio-org/mod-email#configuration), 

> If mod-email couldn't find SMTP configuration in its own DB, it'll try to fetch one from mod-configuration, copy it to the DB and then delete it from mod-configuration.

- [x] Should LOGIN-SAML be added?
- [x] update prod.yml in vault

**Comment by jgreben** [comment]
LOGIN-SAML is handled by https://docs.google.com/document/d/1TO-AybFAECwZt2lGxlw6MDWBNlXuhK3E2liyC2QHA6M/edit#

**Comment by jgreben** [comment]
Fixed also by https://github.com/sul-dlss/folio-tasks/pull/184
