### ISSUE TITLE
New rake task for mod-email configuration

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss-deprecated/folio-migration-tasks#186]
`SMTP_SERVER` is no longer configured through okapi config entries in Nolana. Per the [mod-email readme](https://github.com/folio-org/mod-email#configuration),

> If mod-email couldn't find SMTP configuration in its own DB, it'll try to fetch one from mod-configuration, copy it to the DB and then delete it from mod-configuration.

New [API for email configuration](https://github.com/folio-org/mod-email#api). We can use the files in `json/email` in Folio Ops Migration Files drive.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio-tasks/pull/184
