### ISSUE TITLE
add configuration for event logging and login attempts

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss-deprecated/folio-migration-tasks#195]
See https://github.com/folio-org/mod-login#mod-configuration-entries
It doesn't look like the [folio-helm chart](https://github.com/sul-dlss/folio-helm/blob/master/mod-login/values.yaml) has a parameter we can pass for [configuring mod-login](https://github.com/folio-org/mod-login#module-properties) to change `login.fail.attempts` so maybe create a config entry for it instead of updating the helm chart.

**Comment by shelleydoljack** [comment]
Increase `login.fail.attempts` to 10 and turn on all event logging (including STATUS? not sure what that logs).

**Comment by shelleydoljack** [comment]
This doesn't seem to work when setting failed.login.attempts to 10 in mod-configuration and doing `helm upgrade` and `helm uninstall/helm install`. Maybe try setting a command-line argument in our helm chart.

**Comment by shelleydoljack** [comment]
One question I have is why it worked using mod-configuration when setting to 1 but not 10. Does the setting not apply when greater than the default? Also, mod-configuration is getting replaced by mod-settings in Orchid so maybe changing our helm chart is the best option.

**Comment by shelleydoljack** [comment]
Removed these configurations from our folio environment b/c it doesn't work and it seems it may slow down logging in a bit, which may be related to timeouts we have seen on folio-test and folio-stage when loading data. I'm going to move this to backlog as maybe a post cut-over thing.

**Comment by dlrueda** [comment]
Token rotation is a thing in Orchid so we don’t need to solve this for Nolana
