### ISSUE TITLE
Add CORAL organizations load task

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss-deprecated/folio-migration-tasks#2]
Updated spreadsheet in [migrations folder](https://drive.google.com/drive/u/0/folders/105UT7uKUzK1-yeHF8E-U9DgUjKaOqzbv) 

Column headers are named the same as the fields for organization. Need to add "-SUL" to end of code, status=Active, acq unit = SUL, isVendor = false.

**Comment by jermnelson** [comment]
@shelleydoljack and @dlrueda do these organizations have a category? (i.e. Customer Service, Payments, Returns, Shipments, or Claim)

**Comment by shelleydoljack** [comment]
Do you mean a category for the URL? Not that I'm aware. Here's a link to the meeting notes about this mapping: https://docs.google.com/document/d/11SUtfx70EmkMxiQ64aLqckR5w1KqEe_h2FGu1kGY8hI/edit#bookmark=id.vs9r2tl6pgd

**Comment by jermnelson** [comment]
Yes, sorry the category for the URL. When testing the post of the object, here is the result back from Okapi:

```bash
{"id"=>"601bc66e-d55e-4df0-8c4a-4c2fe20d58d0",
 "name"=>"International Atomic Energy Agency",
 "code"=>"IAEA-SUL",
 "exportToAccounting"=>false,
 "status"=>"Active",
 "aliases"=>[],
 "addresses"=>[],
 "phoneNumbers"=>[],
 "emails"=>[],
 "urls"=>[{"value"=>"http://www.iaea.org/", "categories"=>[]}],
 "contacts"=>[],
 "agreements"=>[],
 "vendorCurrencies"=>[],
 "interfaces"=>[],
 "accounts"=>[],
 "isVendor"=>false,
 "changelogs"=>[],
 "acqUnitIds"=>["29a2be08-d7bc-4e44-bb61-c6bf8f0d15c4"],
 "metadata"=>
  {"createdDate"=>"2022-05-27T16:09:44.445+00:00",
   "createdByUserId"=>"6fb5a144-e9e6-46e7-a939-0d5a0eddb325",
   "updatedDate"=>"2022-05-27T16:09:44.445+00:00",
   "updatedByUserId"=>"6fb5a144-e9e6-46e7-a939-0d5a0eddb325"}}
```

**Comment by shelleydoljack** [comment]
Looks like it created the org and categories doesn't seem to be required.
