### ISSUE TITLE
Add Law service points to tsv

### ISSUE THREAD

**Issue by Laszlo-J** [sul-dlss-deprecated/folio-migration-tasks#206]

**Comment by Laszlo-J** [comment]
Add Law testing service points to tsv file: Law - Book Cabinet and Law - Tech Services

**Comment by shelleydoljack** [comment]
I updated the service-points.tsv in Folio Ops drive with these 2 service points. @dlrueda there are associated locations with these service points that required an update to locations.tsv (adding the service point code). Not sure what to do about the service point LAW- Tech Services. It has 2 assigned primary locations: LAW-TS and LAW-TECHSHADOW. The LAW-TS is not in the locations.tsv file but LAW-TECHSHADOW is so I only added LAW-TS servicepoint code to the LAW-TECHSHADOW location and uploaded the change in locations.tsv to folio ops drive.
