### ISSUE TITLE
Create code to extract data from FOLIO test instance

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss-deprecated/folio-migration-tasks#22]
From json, note which data we need.
Most of the commands to get that data are in the readme, but make sure some aren’t missing.

Create script/rake task to extract the data so easier to do in the moment when migrating.

Add to Data Migration document

**Comment by jgreben** [comment]
We have the code in place to do this and the step is noted on the migration checklist. If there is any missing json data, or new things come up, we can create new tickets and methods to add that json to the existing task group.
