### ISSUE TITLE
Add new holdings types to -stage, -dev, -prod

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#227]
https://drive.google.com/drive/folders/1Nn-PNgniSUH3b_Hi6f2NMNLCXYCWU7Um?usp=share_link

**Comment by shelleydoljack** [comment]
Loaded to -stage. This should get loaded to prod as we refresh it with nothing else to do except make sure @jgreben has the latest files for what is in Folio Ops migration files drive.
