### ISSUE TITLE
remove mapping to affiliate-sponsored-eresources

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss-deprecated/folio-migration-tasks#243]
After discussion with circ subgroup, we no longer want to create user records in FOLIO for folks with privgroups stanford:affiliate-sponsored and stanford:library-eresources-eligible. Not all of them will be given borrowing privileges, and staff will create user records manually for any users that actually should have borrowing privs (hospital residents)

Currently have code:

  def affiliate_sponsored_eresources
    @priv_groups.include?('stanford:affiliate-sponsored') &&
      @priv_groups.include?('stanford:library-eresources-eligible')
  end

So probably just need to remove that def???

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio-tasks/pull/246
