### ISSUE TITLE
Confirm we are mapping display name for FOLIO name data

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss-deprecated/folio-migration-tasks#245]
Are we pulling from name type=“display” from xml document?

xml doc first has 
 <name type="registered" visibility="none">Rueda, Darsi Lee
        <first nval="darsi">Darsi</first>
        <middle nval="lee">Lee</middle>
        <last nval="rueda">Rueda</last>
    </name>

then has 
<name type="display" visibility="world">Rueda, Darsi L
        <first nval="darsi">Darsi</first>
        <middle nval="l">L</middle>
        <last nval="rueda">Rueda</last>
    </name>

The preferred name that a user specifies in Axess/PeopleSoft is in the type=“display” name section, and this is what we should be pulling.

In xslt code we have 

                
                
                
                <xsl:variable name="display_name">
                        <xsl:choose>
                                <xsl:when test="name[@type='display']/first">
                                        <xsl:text>true</xsl:text>
                                </xsl:when>
                                <xsl:otherwise>
                                        <xsl:text>false</xsl:text>
                                </xsl:otherwise>
                        </xsl:choose>
                </xsl:variable>
                <xsl:variable name="USER_FIRST_NAME">
                        <xsl:choose>
                                <xsl:when test="$display_name = 'true'">
                                        <xsl:value-of select="name[@type='display']/first"/>
                                </xsl:when>
                                <xsl:otherwise>
                                        <xsl:value-of select="name[@type='registered']/first" />
                                </xsl:otherwise>
                        </xsl:choose>
                </xsl:variable>
                <xsl:variable name="USER_MIDDLE_NAME">
                        <xsl:choose>
                                <xsl:when test="$display_name = 'true'">
                                        <xsl:value-of select="name[@type='display']/middle"/>
                                </xsl:when>
                                <xsl:otherwise>
                                        <xsl:value-of select="name[@type='registered']/middle"/>
                                </xsl:otherwise>
                        </xsl:choose>
                </xsl:variable>
                <xsl:variable name="USER_LAST_NAME">
                        <xsl:choose>
                                <xsl:when test="$display_name = 'true'">
                                        <xsl:value-of select="name[@type='display']/last"/>
                                </xsl:when>
                                <xsl:otherwise>
                                        <xsl:value-of select="name[@type='registered']/last" />
                                </xsl:otherwise>
                        </xsl:choose>
                </xsl:variable>

Confirm that we are using `name type=“display”` when exists.

**Comment by shelleydoljack** [comment]
Yes, we are: https://github.com/sul-dlss/folio-tasks/blob/592bf61cd190c12ca21173947cb49fe22ecea2a0/lib/xml_user.rb#L50
