### ISSUE TITLE
ILLiad user load consumes file that is not all json data

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss-deprecated/folio-migration-tasks#264]
https://github.com/sul-dlss/folio-tasks/blob/8c28d522c44f86bd540e5fb6db9afde0fac5b3fb/run/folio-userload.sh#L14C3-L14C3

The ILLiad user load is getting this file to process, but it contains non-JSON data, thus we see this error in the load email:
```
rake aborted!
JSON::ParserError: 783: unexpected token at '{"message"=>"Users were imported successfully.",
'
```
The file that the ILLiad process is consuming looks like this:
```
{"message"=>"Users were imported successfully.",
 "createdRecords"=>0,
 "updatedRecords"=>3,
 "failedRecords"=>0,
 "failedUsers"=>[],
 "totalRecords"=>3}
{"users":[{"username":" ... <snip>
```

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio-tasks/pull/265
