### ISSUE TITLE
ABLE: staff report \ in front of call number

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#275]
Reported to have started on 11/2 (during which time we were troubleshooting another issue).

**Comment by jgreben** [comment]
The placement of the slashes can be configured in the ABLE client using the z-link mapping call number rules.

**Comment by ahafele** [comment]
Tested again and no longer seeing \ in front of call number. 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVN1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c9a3a4c99a3ef3f7532c5eb9c1cceb5d1369166/Screen%20Shot%202023-11-07%20at%207.24.53%20AM.png)
