### ISSUE TITLE
Spinomatic - wrong call number type fix

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#291]
Work appears to have been merged [here](https://github.com/sul-dlss/folio-setae-api/pull/7) after user verifying fix on test. Not working correctly on production - see [comment](https://github.com/sul-dlss/folio-setae-api/pull/7#issuecomment-1954646997)

**Comment by jermnelson** [comment]
@ahafele the pods in Production were using an old container version. I just redeployed and the current container is now running in these pods if you want to test again.

**Comment by ahafele** [comment]
Looks good, thank you!
