### ISSUE TITLE
Poppy Integration Testing - SelfCheck, Meescan and Law LibCabinets

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#292]
- [x] Lyngsoe law cabinets - Will
- Selfcheck - 
  - [ ] Kent
  - [x] Mike Nack
  - [ ] Roy/Lorna
- [ ] Meescan - Will, Thomas (meescan rep)

**Comment by ahafele** [comment]
@jgreben is this ready to be tested with Poppy on folio-test?

**Comment by jgreben** [comment]
No, we are waiting for the resolution of:
https://folio-org.atlassian.net/browse/SIP2-190
https://folio-org.atlassian.net/browse/SIP2-191

Alternately we can decide not to upgrade egde-sip2 and test it with the old version of that.

**Comment by ahafele** [comment]
Still need to check Meescan. The rest are working.

**Comment by dlrueda** [comment]
Will says we've tested Meescan and it works.
