### ISSUE TITLE
Poppy Integration Testing - caiasoft

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#293]
Reach out to Jeanette for testing?

**Comment by dlrueda** [comment]
Creating testing plan with Laura. Need to get her new authentication endpoint to create okapi token

**Comment by dlrueda** [comment]
authentication working.

refiles/retrievals good.  problem with accessions and location updates
fixed and re-tested 5/23, all good.

had to update UUID for itemNoteType, used to be different on test and prod, now they're the same after refresh.

Caiasoft is good to go
