### ISSUE TITLE
Poppy Integration Testing - ILLIAD and Borrowdirect

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#296]
Reach out to Hilary for testing.

**Comment by ahafele** [comment]
Darsi will reach out to Hilary

**Comment by dlrueda** [comment]
Hilary: The lookup looks okay for ILLiad-FOLIO test.

**Comment by dlrueda** [comment]
We've set up Reshare's test system to point to folio-test, and Debra has figured out the right URL for z39.50 lookups.  Waiting on her testing results

**Comment by ahafele** [comment]
Upgrade to Poppy complete
