### ISSUE TITLE
Poppy Integration Testing - Cybersource

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#298]
Josh and SW team

**Comment by dlrueda** [comment]
Really what we need to test is that the Folio api call to pay the bill is successful under Poppy.

MyLibrary interacts with Cybersource, payment with CC is made there, on success response to MyLibrary the api is called to Folio to pay that bill off.

**Comment by dlrueda** [comment]
Monthly report of Cybersource payments in Folio also needs to be checked that it will work in Poppy.

Let's not test this beforehand, if it fails after upgrade then we can triage it then.
We can see if the GET has changed cuz that's what is used.
Has this module (fee-fines) version changed for Poppy?

**Comment by dlrueda** [comment]
Look at MyLibrary code to see what the response is from Cybersource, what the body of the POST is to FOLLO, and the API call is to make the payment in FOLIO. 

Confirm that the API call still works in Poppy
curl to accounts endpoint

**Comment by jgreben** [comment]
mod-feesfines-19.0.0 uses the same accounts-bulk/pay endpoint as the current prod version: https://github.com/folio-org/mod-feesfines/blob/5eca8f523b5a901640be5135e8513bd71f772653/ramls/accounts-bulk.raml#L90

I was able to perform a POST to `accounts-bulk/pay` in the current folio-stage poppy environment using the same json body as shown here: https://github.com/sul-dlss/mylibrary/blob/acb3c75068e9cbf36526ab2c74b0901dee848e0e/app/services/folio_client.rb#L209-L221

**Comment by jgreben** [comment]
Done.
