### ISSUE TITLE
Create task for adding Acquisitions Method (Lotus)

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#30]
Values that need to be added are here -https://drive.google.com/drive/folders/1hrXK5nNDE7xTNHbvCs7KW-UheMyn_0uF acquisitions/acquisitions-methods.tsv

@shelleydoljack does it need a Source value? 

Blocked by #4 ?

**Comment by shelleydoljack** [comment]
Actually, this ticket blocks #4 since we cannot create orders that use acquisitions methods that we haven't created yet. For source value, only User and System are accepted values so I think we'll use "User" since "System" seems to be for the default reference data.
