### ISSUE TITLE
Update existing boundwiths to include primary relationship

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#304]
Boundwith relationships should include a bound-with-part object for the actual item and holdings. This will resolve the UI display issues noted in Poppy testing. 

Open question - do we want to update the data in Nolana or Poppy?

Background in #629

**Comment by shelleydoljack** [comment]
Wrote a script, get_bwprinciple_holdingsRecordIds.sh, that outputs a comma-separated file of bwprinciple item IDs and holdings IDs. Running on folio-test, the resulting file is 34,991 rows. If we use the bw dag to create the relationships, we'd have to split it into 350 files, which seems like too much manual work. 

It seems the quickest option is to add to folio-tasks a create_bw_task that just does all those POSTs to create the relationships.

**Comment by shelleydoljack** [comment]
New code in PR https://github.com/sul-dlss/folio-tasks/pull/305
Running it again folio-test now. It took 10 minutes to process 3,076. The rake task quit when, presumably, my laptop went to sleep (I went to lunch). It's running again for the rest of the UUIDs in the file. Estimated total time for 34,991 rows to process is 113 minutes.

**Comment by shelleydoljack** [comment]
Took 2 hrs 10 min to run on folio-test.

**Comment by shelleydoljack** [comment]
@ahafele Should the holdings type for the bw principle be bound-with? Here's an example of a bw principle holdings record (UUID `b6971387-f447-551d-b026-4a894b3cf024`) https://folio-test.stanford.edu/inventory/view/1457d811-ca7b-5bd2-9d92-6c9ea5b7d77b/b6971387-f447-551d-b026-4a894b3cf024?qindex=hid&query=b6971387-f447-551d-b026-4a894b3cf024&segment=holdings&sort=title

**Comment by ahafele** [comment]
@shelleydoljack No - the idea being that the principle holdings could have other items that are not bound-withs.

**Comment by shelleydoljack** [comment]
Thank goodness! Let me know when I should update the data on folio-stage.

**Comment by ahafele** [comment]
@shelleydoljack I didn't hear back from Jeanette today, but I did some QA and all looked good to me. I think you are safe to update stage as well. FYI Suzette is doing some rollover testing there today.

**Comment by shelleydoljack** [comment]
Updated folio-stage. Took about 20 minutes to run from sul-libsys-deploy server.

**Comment by ahafele** [comment]
@shelleydoljack  Jeanette and I reviewed production SearchWorks and all looks good. We can now update FOLIO data on production to include the principle relationship.

**Comment by shelleydoljack** [comment]
Updated folio-prod. Started 2024-06-03T17:24:46.484+00:00 finished 2024-06-03T17:46:11.508+00:00. Input file of bwparent records was 35,149 lines. Currently there are now 235,238 boundwith parts relationships in `inventory-storage/bound-with-parts`.
