### ISSUE TITLE
Update Lehigh Tool config for FY25

### ISSUE THREAD

**Issue by ahafele** [sul-dlss-deprecated/folio-migration-tasks#310]
SUL Production - https://folio-orders.stanford.edu/ 
Law Production - https://folio-orders-law.stanford.edu/ 
SUL Stage - https://folio-orders-dev.stanford.edu/
Law Stage - https://folio-orders-law-dev.stanford.edu/

configurations need to be changed to fiscalYearCode: SUL2025 for SUL and LAW2025 for Law

**Comment by jermnelson** [comment]
All four Lehigh Tool environments have been updated to FY 2025.
