### ISSUE TITLE
Update rake task that assigns user permissions to add service point

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss-deprecated/folio-migration-tasks#32]

**Comment by dlrueda** [comment]
There is a rake task to assign permission sets to a user, using the pset assignment tab of the permissions matrix spreadsheet:
https://docs.google.com/spreadsheets/d/1jfU6Bww6gXd81HREYVp8OBItYTFNJwwqMTLxJncZomQ/edit#gid=625131215

I have added a new column (3rd column) for service point.

Update rake task to adjust columns for this new one, and assign this service point to the user. It should also be assigned as the default service point.

**Comment by dlrueda** [comment]
ok to have <none> assigned as service point

**Comment by jermnelson** [comment]
Closed by PR https://github.com/sul-dlss/folio-tasks/pull/37
