### ISSUE TITLE
Extract circ reference data from current FOLIO instance

### ISSUE THREAD

**Issue by dlrueda** [sul-dlss-deprecated/folio-migration-tasks#46]

**Comment by dlrueda** [comment]
Need to extract all the different types of circulation settings that the circ subgroup has been creating.  Laszlo will provide list.

Only provide a data element if we have created something beyond the default reference data supplied in Lotus.  We don’t want to create duplicate data, or have too many failures when we try to load because it already exists.

**Comment by Laszlo-J** [comment]
Circulation > General > Circ rules
Circulation > Loans > Fixed due date schedules
Circulation > Loans > Loan policies
Circulation > Fee/fine > Overdue fine policy
Circulation > Fee/fine > Lost item fee policy
Circulation > Patron notices > Patron notice policies
Circulation > Patron notices > Patron notice templates
Circulation > Requests > Request cancellation reasons
Circulation > Requests > Request policies
Courses > Terms	
Courses > Course departments
Users > Fee/fine > Manual charges

**Comment by Laszlo-J** [comment]
Also added anything not yet listed to the data migration sheet [https://docs.google.com/spreadsheets/d/1MNTMtwdR-b_eHmfQ4IrGTrYKZimoLWLtpD-dlrISQAo/edit#gid=0](url)
