### ISSUE TITLE
Change organizations mapping for vendors

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss-deprecated/folio-migration-tasks#5]
Pending investigation on ticket https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/104

Small tweaks to vendor mapping:

`<vendorCurrency>` = vendor currency
`<claimPeriod>` = claiming interval (in days)
when `<vendorID>` ends with “-9999” for SUL vendors, set `exportToAccounting = false`
pending answers from Business and LAW for setting `exportToAccounting`

**Comment by shelleydoljack** [comment]
Need data for vendorCurrency from Symphony and mapping to ISO-4217 (which I'm guessing is the currency code standard FOLIO uses (i've not had much luck figuring out what the currency codes are that FOLIO uses searching slack and the github repos)).

**Comment by scanedastanford** [comment]
`<addressCategory>` = address category (will be Orders, Payments, or Claims or some combination)
`<addressIdx>1</addressIdx>` = primary address (applies to phones and emails)
For SUL and Law, when `<vendorID>` ends with “-9999”, `set exportToAccounting = false`
For Business, when `<vendorID>` ends with “-999”, `set exportToAccounting = false`

**Comment by shelleydoljack** [comment]
New XML files added to the Folio Ops migration files in gdrive.

**Comment by shelleydoljack** [comment]
For cases where one vendorAddress node with `<addressIdx>1</addressIdx>` has multiple email address entries in `<entry name="E-Address">` and `<entry name="Email for po/claim">`, make `<entry name="Email for po/claim">` primary email address. If no "Email fo po/claim", then the "E-Address" should be primary.
