### ISSUE TITLE
Investigate why assign service points does not update default service point in user records.

### ISSUE THREAD

**Issue by jgreben** [sul-dlss-deprecated/folio-migration-tasks#62]
`tsv_users:assign_service_points` updates the `/request-preference-storage/request-preference/` endpoint, but this default does not appear in the user record. Investigate why and maybe use the `mod-user-import` endpoint instead?

**Comment by shelleydoljack** [comment]
The bootstrap superuser script uses the `/service-points-users` endpoint to assign service point to the user. See https://github.com/sul-dlss/folio-k8s/blob/a532824e95242b3dbefe5d93c56bf75ec0bc2d3c/docker/bootstrap-superuser/bootstrap-superuser.pl#L117-L126 . We probably want to add a [PUT /service-points-users/{servicePointsUserId}](https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/service-points-user.html#service_points_users__servicepointsuserid__put) method to the [UsersTaskHelpers](https://github.com/sul-dlss/folio-tasks/blob/main/tasks/helpers/users.rb). I added [a POST method](https://github.com/sul-dlss/folio-tasks/blob/1702fbe698031b1261f2279754ee2f96f630574f/tasks/helpers/users.rb#L82-L84) as part of the PR to add app users.

**Comment by shelleydoljack** [comment]
Actually, maybe using `mod-user-import` is better since it seems there is some business logic associated with user creation and we aren't seeing the whole picture posting and putting to different endpoints.

**Comment by shelleydoljack** [comment]
I edited the app_discovery user in folio-test on-prem to find out what's going on. There are two places default service point is used. One place, which is coming from the `/service-points-users` endpoint, shows up in the top right corner when the user logs into FOLIO and in the "Service Point" section when viewing the user record:
![Screen Shot 2022-07-21 at 12 34 29 PM](https://user-images.githubusercontent.com/6343464/180289659-b20786bd-e5a3-4f20-b7db-ebd71c29dc8d.png)

This is the response for the app_discovery user when querying the `/service-points-users` endpoint:
![Screen Shot 2022-07-21 at 12 37 02 PM](https://user-images.githubusercontent.com/6343464/180289943-3f4d8421-dd68-4022-89cb-82817dc0d508.png)

The other place, which the rake task is doing, is a PUT to `/request-preference-storage/request-preference/` endpoint. This is specifically for the request preference. From the user record, it looks like this:
![Screen Shot 2022-07-21 at 12 34 23 PM](https://user-images.githubusercontent.com/6343464/180289632-76b27553-552c-44b0-ada6-62fbc53a5ccc.png)

From querying the endpoint:
![Screen Shot 2022-07-21 at 12 34 39 PM](https://user-images.githubusercontent.com/6343464/180289552-27bf9a53-bd56-4084-a10a-62d8edf268b9.png)

Before I added a value to "Default pickup service point" in FOLIO, there was no value for "defaultServicePointId" from `/request-preference-storage/request-preference?query=userId==9b6384ad-e9e8-4807-9afc-04586e400f1e`.

The rake task is only assigning the default service point for requests. We need to add a post to `/service-point-users` and maybe remove the PUT to `/request-preference-storage` (do staff users need this set?).

**Comment by jgreben** [comment]
Agreed and thanks for looking into this. The staff users for the rake task do not need the request preference service point set. (At some point we may want to figure out what to set during the user import for all users.) I will make a ticket to change the rake task to use the service-point-users endpoint.
