### ISSUE TITLE
Map user MXFEE-BUS to BUS-guest user group

### ISSUE THREAD

**Issue by Laszlo-J** [sul-dlss-deprecated/folio-migration-tasks#77]
GSB decided to fold them in with this FOLIO user group. Update tsv file and map when importing users.

[https://docs.google.com/spreadsheets/d/10n77Zxgp3GCgwB9pPR80CZzNs6ERDzQkyCuolUQEoG0/edit#gid=221919063&range=E3](url)

**Comment by jgreben** [comment]
The symphony patron profiles are not mapped in the userload, only affiliation types are mapped to patron groups, and FEE users are not loaded during the userload. We have a BUS-guest patron group in folio (https://drive.google.com/drive/folders/0AFrAJFZgw_8UUk9PVA) and they can use that when creating new BUS-guest users.
