### ISSUE TITLE
Add task to load test user accounts

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss-deprecated/folio-migration-tasks#78]
Some test user accounts created by the circ subgroup to add to a new spreadsheet and new task to just load test users to non-prod systems: https://docs.google.com/document/u/0/d/1tQt__IW_v_lWkhH4msWvIzNotHhL3L391GrOLZsSRJQ/edit

**Comment by jgreben** [comment]
Similar to or refactor load app user task. Update permissions matrix as needed.

**Comment by jgreben** [comment]
Fixed by https://github.com/sul-dlss/folio-tasks/pull/86
